baseurl = "https://blog.nitya.dev"
DefaultContentLanguage = "en"
title = "Connecting Dots"
theme = "beautifulhugo"
paginate = 3
enableGitInfo = true

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "G-NP5Z83F9EN"

[Params]
# homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Applications﹒AI﹒Automation"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "Jan 2, 2006"
  commit = "https://github.com/nitya/blog/tree/" #false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  gcse = "d2229a0a74b7c4548" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Nitya Narasimhan"
  website = "nitya.dev"
  github = "nitya"
  dev = "nitya"
  twitter = "nitya"
  linkedin = "nityan"
  instagram = "sketchthedocs"
  #email = "hello@nitya.dev"
  #mastodon = "https://fosstodon.org/@nitya"
  #youtube = "user/username" # or channel/channelname
  #facebook = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #discord = "invite code (https://discord.gg/XXXXXXX)"
  #strava = "userid"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About Me"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "collections"
    name = "Collections"
    weight = 2

[[menu.main]]
    parent = "collections"
    name = "Applications"
    url = "page/applications/"
    weight = 1

[[menu.main]]
    parent = "collections"
    name = "AI ML"
    url = "page/aiml/"
    weight = 2

[[menu.main]]
    parent = "collections"
    name = "Automation"
    url = "page/automation/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
